### ISSUE TITLE
_site/assets not updating when adding files to _assets folder

### ISSUE THREAD

**Issue by enigmabeautysalon** [nielsenramon/kickster#19]
Whenever I add a new file (image or .css or whatever) to _assets folder, the _site/assets is not updating.
Hence, the generated file gives an error of files not found.

```
Regenerating: 1 file(s) changed at 2016-08-10 15:27:19 ...done in 32.98629
6 seconds.
[2016-08-10 15:27:56] ERROR `/assets/frameworks.css' not found.
[2016-08-10 15:28:24] ERROR `/assets/frameworks.css' not found.
```

Update:
Apparently, you have to use/call those assets to be included in the _site folder.
I've used `@import` for frameworks.css so I guess that doesn't work

**Comment by nielsenramon** [comment]
@enigmabeautysalon You have to add css files into the `stylesheets` directory so `jekyll-assets` can pick it up :).

**Comment by jhabdas** [comment]
@enigmabeautysalon Please close this if it's no longer an issue.
