### ISSUE TITLE
Add option to publish to 'master' branch

### ISSUE THREAD

**Issue by Nuruddinjr** [nielsenramon/kickster#21]
I publish my organization page to master branch, to run on given domain,so can you please add support for deployment to master branch using kickster

**Comment by nielsenramon** [comment]
@Nuruddinjr You can also run a given domain on gh-pages branch :) it works exactly the same.
If you want to deploy to master you can edit the bin/deploy script to push to master instead of gh-pages.

**Comment by Nuruddinjr** [comment]
My bad, Let me try =)
