### ISSUE TITLE
Jekyll-assets issue?

### ISSUE THREAD

**Issue by FalkoJoseph** [nielsenramon/kickster#24]
Newly added assets in the `/_assets` directory (images) don't seem to be copied over to the `_site` directory.

Adding below code in `_config.yml` fixed it for me though. (Got this from the [Jekyll-assets docs](https://github.com/jekyll/jekyll-assets#configuration)).

```
assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"
```

So my question is: did I overlook something else, or is this a bug? :)

**Comment by nielsenramon** [comment]
@FalkoJoseph Hmmm I can't replicate your issue. Just scaffolded a new project and added one image. Imported that image in my index.html like this: `<img src="{% asset_path test.jpg %}" alt="">`. Works without issues.

Did you run bin/setup without issues? What version of jekyll-assets are you running?

**Comment by FalkoJoseph** [comment]
@nielsenramon fixed it using `asset_path` instead. I guess it's how the asset pipeline detects what images to copy over. Thanks for the tip 🎉
