### ISSUE TITLE
Perform a bower install on bin/setup

### ISSUE THREAD

**Issue by FalkoJoseph** [nielsenramon/kickster#7]
After installation it should install dependencies from other package managers as well, don't you think?

**Comment by nielsenramon** [comment]
@FalkoJoseph How would you see that working? And what package manager do you wish to see included?

**Comment by FalkoJoseph** [comment]
@nielsenramon once you do `kickster new site_name` it should execute `bin/setup`. So you can get started right away. Seems a bit more convenient.
